CREATE SCHEMA IF NOT EXISTS oms;
CREATE TABLE IF NOT EXISTS oms.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   street VARCHAR(255),
   phone VARCHAR(255),
   city VARCHAR(255),
   state VARCHAR(255),
   profile_pic_url VARCHAR(255),
   country VARCHAR(255),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oms.category  (
id bigserial NOT NULL,
    name TEXT NOT NULL,
    parent_category int,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oms.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   description VARCHAR(255),
   unit_price INTEGER NOT NULL,
   category_id BIGINT NOT NULL,
   CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE  IF NOT EXISTS  oms.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   customer_id BIGINT NOT NULL,
   status VARCHAR(255),
   total_quantity INTEGER NOT NULL,
   total_price INTEGER NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_orders PRIMARY KEY (id)
);

-- oms.orders foreign keys

CREATE TABLE IF NOT EXISTS oms.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_id BIGINT NOT NULL,
   quantity INTEGER NOT NULL,
   price INTEGER NOT NULL,
   row_total INTEGER NOT NULL,
   order_id BIGINT NOT NULL,
   CONSTRAINT pk_orderitems PRIMARY KEY (id)
);